services:
  book-api:
    build: .
    ports:
      - "9090:9090"
    volumes:
      - ./certs:/app/certs
    environment:
      - PORT=9090
      - HOST=0.0.0.0
      - JWT=your_super_secret_key
      - CLIENT=client
      - SECRET=secret
      - KEY=certs/key.pem
      - CERTIFICATE=certs/cert.pem
      - VERBOSE=0
